language: node_js

node_js:
    - 0.10.32

before_install:
    - npm install -g gulp

install:
    - npm install

script:
    - gulp ci

branches:
    only:
        - master

after_script:
    - cat lcov.info | codeclimate

addons:
    code-climate:
        repo-token: 3b3b855c93bf2d870a29b319ba03b5ad0edaf79fd7a6d94e038d49c6cb2a7d95
